---
- name: Install Apache
  yum: name={{ item }} state=present
  with_items:
   - httpd

- include: apache_standard-config.yml
# Enable ssl and security
#- include: apache-ssl-with-cert.yml

- name: Copy Apache config
  template: src=whydah.conf dest=/etc/httpd/conf.d/whydah.conf owner=root group=root mode=644 backup=true

#- name: Copy Apache config with ssl certificate
#  template: src=whydah-ssl.conf dest=/etc/httpd/conf.d/whydah.conf owner=root group=root mode=644 backup=true

- name: restart apache
  service: name=httpd state=restarted enabled=yes